import Head from "next/head";
import { Inter } from "@next/font/google";
import { About, Footer, Header, Navbar, Howitworks } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Waste AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Header />
        <About />
        <Howitworks />
      </main>
      <Footer />
    </>
  );
}
